config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do
  root to: 'users#index'

  get 'signup', to: 'members#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  resources :users
  resources :guests
  resources :members
  resources :sessions
  resources :passwords
  resources :products
  resources :articles do
    resources :comments
  end

  resources :projects
  resources :tasks
  mount Sidekiq::Web, at:'/sidekiq'
  # get '(errors)/:status', to: "errors#show", constraints: {status: /\d{3}/}
end

app/models/article.rb
class Article < ActiveRecord::Base
  belongs_to :author
  has_many :comments
  scope :published, -> { where("published_at < ?", Time.zone.now) }

  after_commit :flush_cache
  def flush_cache
   	Rails.cache.delete([self.class.name, id])
    Rails.cache.delete([self.class.name, "published"])
   end	
  
  def self.cached_find(id)
    Rails.cache.fetch([name, id], expires_in: 5.minutes ) {find(id)}
  end

  def self.cached_published
    Rails.cache.fetch([self, 'published'], expires_in: 5.minutes) { published }
  end  

  def cached_comments_count
  	Rails.cache.fetch([self, 'comments_count']) { comments.size }
  end

  def cached_comments
    Rails.cache.fetch([self, "comments"]) { comments.to_a }
  end

  def cached_article
  	Rails.cache.fetch([self.class.name, id]) { find(id) }
  end

  def cached_author
  	Author.cached_find(author_id)
  end	
end

app/models/author.rb
class Author < ActiveRecord::Base
  has_many :articles

  after_commit :flush_cache
  
  def self.cached_find(id)
    Rails.cache.fetch([name, id], expires_in: 5.minutes) { find(id) }
  end
  
  def flush_cache
    Rails.cache.delete([self.class.name, id])
  end
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :products
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  # 典型的用法在many-to-one时，当many端发生改变时，更新one端的updated_at时间。
  belongs_to :article, touch: true
  format_url :website
end

app/models/guest.rb
class Guest < User
	
  def guest?
 	true
  end
  
  def move_to(user)
    project.tasks.update_all(user_id: user.id)
  end
  
  def name
    "Guest"
  end

  def task_limit
    10
  end
  
  def can_share_task?(task)
    false
  end
  
  def send_password_reset
  end
end

app/models/member.rb
class Member < User
  has_one :profile
  has_secure_password
  def guest?
    false
  end
  
  def name
    username
  end

  def task_limit
    1000
  end
  
  def can_share_task?(task)
    task.project.user_id == id
  end
  
  def send_password_reset
    UserMailer.password_reset(self).deliver
  end
end

app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :category

  def update_with_conflict_validation(*args)
  	update_attributes(*args)
  rescue ActiveRecord::StaleObjectError
  	self.lock_version = lock_version_was
  	errors.add :base, "This record changed while you were editing."	
  	changes.except("updated_at").each do |name, values|
  	  errors.add name, "was #{values.first}"
    end
    false		
  end	
end

app/models/profile.rb
class Profile < ActiveRecord::Base
  belongs_to :user
end

app/models/project.rb
class Project < ActiveRecord::Base
  has_many :tasks
  belongs_to :user
  def incomplete_tasks
    tasks.where(completed_at: nil)
  end

  def complete_tasks
    tasks.where('completed_at is not null')
  end
end

app/models/snippet.rb
class Snippet < ActiveRecord::Base
end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :project

  def complete
    completed_at.present?
  end

  def complete=(value)
    if value.to_i.zero?
      self.completed_at = nil
    else
      self.completed_at = Time.zone.now
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :projects
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    @articles = Article.cached_published
  end

  def show
    @article = Article.cached_find(params[:id])
    @comment = Comment.new
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    if @article.save
      redirect_to articles_url, notice: "Created article."
    else
      render :new
    end
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])
    if @article.update_attributes(article_params)
      redirect_to @article, notice: "Updated article."
    else
      render :edit
    end
  end

  private
  def article_params
    params.require(:article).permit!
  end  
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_filter :load_article

  def create
    @comment = @article.comments.build(comment_params)
    if @comment.save
      redirect_to @article, notice: "Added comment."
    else
      render :new
    end
  end

private

  def load_article
    @article = Article.find(params[:article_id])
  end

  def comment_params
    params.require(:comment).permit!
  end  
end

app/controllers/errors_controller.rb
class ErrorsController < ApplicationController
  # action_dispatch
  # Rack::Utils::HTTP_STATUS_CODES.fetch(status, Rack::Utils::HTTP_STATUS_CODES[500])
  # detail see https://github.com/rails/rails/blob/master/actionpack/lib/action_dispatch/middleware/public_exceptions.rb
  def show
  	# @exception = <ActionController::RoutingError: No route matches [GET] "/produc00"> 404
  	@exception = env["action_dispatch.exception"]
    respond_to do |format|
      format.html { render action: request.path[1..-1] }
      format.json { render json: {status: request.path[1..-1], error: @exception.message} }
    end
  end	
end

app/controllers/guests_controller.rb
class GuestsController < ApplicationController
  def create
    guest = Guest.create!
    session[:user_id] = guest.id
    redirect_to projects_url
  end
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  def new
    @member = Member.new
  end

  def create
    @member = Member.new(params[:member].permit!)
    if @member.save
      current_user.move_to(@member) if current_user && current_user.guest?
      session[:user_id] = @member.id
      redirect_to root_url
    else
      render "new"
    end
  end

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def create
    @task = Task.create!(task_params)
    redirect_to projects_url
  end

  def update
    @task = Task.find(params[:id])
    @task.update_attributes!(task_params)
    respond_to do |format|
      format.html { redirect_to tasks_url }
      format.js
    end
  end

  def destroy
    @task = Task.destroy(params[:id])
    respond_to do |format|
      format.html { redirect_to tasks_url }
      format.js
    end
  end

  private
  def task_params
    params.require(:task).permit!
  end  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @signup_form = SignupForm.new
  end

  def create
    @signup_form = SignupForm.new
    if @signup_form.submit(user_params)
      session[:user_id] = @signup_form.user.id
      redirect_to @signup_form.user, notice: "Thank you for signing up!"
    else
      render "new"
    end
  end

  def show
    @user = current_user
  end

private

  def user_params
    params.require(:user).permit(
      :username, :email, :password, :password_confirmation, :subscribed,
      :twitter_name, :github_name, :bio
    )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/errors_helper.rb
module ErrorsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/articles/_form.html.erb
<%= form_for(@article) do |f| %>
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
      <% @article.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_area :content %>
  </div>
  <div class="actions">
    <%= f.submit "Post Comment" %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Editing article</h1>

<%= render 'form' %>

<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<h1>Articles</h1>

<div id="articles">
  <% @articles.each do |article| %>
    <h2><%= link_to article.name, article %></h2>
    <p class="info">
      Published on <%= article.published_at.strftime("%B %e, %Y") %>
      by <%= article.cached_author.name %>
    </p>
    <%= simple_format article.content %>
    <p><%= link_to pluralize(article.cached_comments_count, "comment"), article %></p>
  <% end %>
</div>

<p><%= link_to "New Article", new_article_path %></p>

app/views/articles/new.html.erb
<h1>New article</h1>

<%= render 'form' %>

<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<h1><%= @article.name %></h1>

<p class="info">
  Published on <%= @article.published_at.strftime("%B %e, %Y") %>
  by <%= @article.cached_author.name %>
</p>

<%= simple_format @article.content %>

<p>
  <%= link_to "Back to Articles", articles_path %> |
  <%= link_to "Edit", edit_article_path(@article) %>
</p>

<h2><%= pluralize(@article.cached_comments_count, "Comment") %></h2>

<div id="comments">
  <%= render @article.cached_comments %>
</div>

<h3>New Comment</h3>

<%= render 'comments/form' %>

app/views/comments/_comment.html.erb
<%= div_for comment do %>
  <p><strong><%= comment.name %> says</strong></p>
  <%= simple_format comment.content %>
<% end %>

app/views/comments/_form.html.erb
<%= form_for [@article, @comment] do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %> <%= f.text_field :name %>
  </div>
   <div class="field">
    <%= f.label :website, "Website URL" %><br />
    <%= f.text_field :website %>
  </div>
  <div class="field">
    <%= f.text_area :content, rows: 8, cols: 30 %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comments/new.html.erb
<h1>Post Comment</h1>

<%= render 'form' %>

<%= link_to 'Back', @article %>

app/views/members/new.html.erb
<h1>Sign Up</h1>

<%= form_for @member do |f| %>
  <% if @member.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% @member.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :username %><br />
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions"><%= f.submit "Sign up" %></div>
<% end %>

app/views/tasks/_task.html.erb
<%= form_for task, remote: true do |f| %>
  <%= f.check_box :complete %>
  <%= f.label :complete, task.name %>
  <%= link_to "(remove)", task, method: :delete, data: {confirm: "Are you sure?"}, remote: true %>
<% end %>

app/views/tasks/create.js.erb
$('#new_task')[0].reset();
$('#incomplete_tasks').append('<%= j render(@task) %>');
$('#edit_task_<%= @task.id %>').submitOnCheck();

app/views/tasks/destroy.js.erb
$('#edit_task_<%= @task.id %>').remove();

app/views/tasks/update.js.erb
<% if @task.complete %>
  $('#edit_task_<%= @task.id %>').appendTo('#complete_tasks');
<% else %>
  $('#edit_task_<%= @task.id %>').appendTo('#incomplete_tasks');
<% end %>

app/views/users/index.html.erb
<h1>Welcome</h1>
<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>

app/views/users/new.html.erb
<%= form_for @signup_form do |f| %>
  <% if @signup_form.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% @signup_form.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :username %><br />
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="field">
    <%= f.check_box :subscribed %>
    <%= f.label :subscribed, "Subscribe to our mailing list." %>
  </div>


  <h3>Profile Details</h3>
  <div class="field">
    <%= f.label :twitter_name %><br />
    <%= f.text_field :twitter_name %>
  </div>
  <div class="field">
    <%= f.label :github_name %><br />
    <%= f.text_field :github_name %>
  </div>
  <div class="field">
    <%= f.label :bio %><br />
    <%= f.text_area :bio, rows: 5, cols: 40 %>
  </div>
  <div class="actions"><%= f.submit "Sign Up" %></div>
<% end %>

app/views/users/show.html.erb
<h1>User Profile</h1>

<p>Username: <%= @user.username %></p>

<p>Email: <%= @user.email %></p>

<% if @user.profile.twitter_name.present? %>
  <p>Twitter: <%= @user.profile.twitter_name %></p>
<% end %>

<% if @user.profile.github_name.present? %>
  <p>GitHub: <%= @user.profile.github_name %></p>
<% end %>

<% if @user.profile.bio.present? %>
  <p>Bio: <%= @user.profile.bio %></p>
<% end %>

<p><%= link_to "Change Password", new_password_path %></p>